name: Publish Node.js Package

on:
  push: 
    branches: [main, release*]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com/'

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Run tests
      - name: Run Tests
        run: npm test

      # Lint the code (optional, recommended for quality checks)
      #- name: Run Linter
      #  run: npm run lint

      # Build the package (if your package has a build step)
      - name: Build Package
        run: npm run build

      # Publish to GitHub Package Registry
      - name: Publish to GitHub Package Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
